---
title: "Investigating a vowel shift in progress in Santiago Laxopa Zapotec"
date: last-modified
author: 
    - name: 
        given: Mykel Loren 
        family: Brinkerhoff
      id: mlb
      orcid: 0000-0002-2190-6544
      email: mlbrinke@uw.edu
      affiliation:
        - name: University of Washington
          city: Seattle
          state: WA
          url: www.uw.edu
abstract: |
    This article investigates a vowel shift in progress in Santiago Laxopa Zapotec's vowel system. Evidence from Pillai Scores and Bhattacharyya's Afinity show that the Sierra Norte Zapotec vowel /o/ is rising to /u/. Male speakers of Santiago Laxopa Zapotec have the largest divergence between [o] and [u] productions.   
keywords: 
    - Vowel Shift
    - Vowel overlap
    - Zapotec 
license: "CC BY"
copyright: 
    holder: Mykel Loren Brinkerhoff
    year: 2026
format: 
    pdf: 
        toc: true
        number-sections: true
        linestretch: 2
        highlight-style: github
        fontenc: utf-8
        mainfont: "Libertinus Serif"
        sansfont: "Libertinus Sans"
---

```{r}
source(here::here(
    "scripts",
    "001_startHere.R")
 )
```

## Introduction

### Vowel splits, mergers, and shifts

#### Previous reseach about splits, mergers, and shifts

#### Quantification through Pillai Scores and Bhattacharyya's Affinity

### Santiago Laxopa Zapotec

Santiago Laxopa Zapotec (SLZ; endonym _Dille'xhunh Laxup_) is an Sierra Norte Zapotec variety spoken by approximately 1000 speakers in the pueblo of Santiago Laxopa [@brinkerhoffUsingResidualH12025,@brinkerhoffVoiceQualityLaryngeal2025]. Most work 

#### Previous vowel research

## Methods

### Data collection

Data was collected in the summer 2022 by myself and a fellow researcher in the pueblo of Santiago Laxopa, Ixtlán, Oaxaca, Mexico. Ten native speaker participants (five female; five male) performed a word list elicitation task consisting of 72 items repeated three times in isolation and three times in the carrier sentence _Shnia' X chonhe lhas_ [ʃnːiaˀ X tʃone ɾas] "I say X three times." Recordings were made using a Zoom H4n handheld recorder (16-bit, 44.5 kHz).

### Data processing

## Analysis

## Results

### Vowel space

### Vowel overlap

### Vowel shift

## Conclusions

## Refernces

:::{#refs}
:::